### ISSUE TITLE
Доработать определение наличия леса

### ISSUE THREAD

**Issue by pavelbezpravel** [moevm/MSE-2023-image-ecology-12#35]
Посмотреть, что выдал чятгпт, чтоб определять, есть ли на снимке лес

**Comment by youngwow** [comment]
ChatGPT:
`Texture analysis: Texture analysis techniques can be used to distinguish between different types of surfaces in an image. Forests typically have a high degree of texture due to the presence of leaves and branches, while non-forested surfaces are generally smoother. Texture analysis can be done using techniques such as the gray-level co-occurrence matrix (GLCM).

Spectral signatures: Different materials reflect different amounts of light at different wavelengths, resulting in unique spectral signatures. By comparing the spectral signature of an area in the image to known spectral signatures of forests, you can determine if the area is forested or not.

These techniques do not require neural networks or machine learning algorithms and can be implemented using traditional image processing and computer vision techniques. However, it's worth noting that machine learning techniques can often provide more accurate results, especially when dealing with complex and variable data.`

Необходимо доработать определение наличия леса с помощь методов: Texture analysis, Spectral signatures.
